name: バグ報告
description: バグ報告用フォーム
title: "記入例: 妖精の像をメインハンドに持った状態でエンドの最下層にカーソルを向けるとサーバーから切断される"
labels:
  - bug
body:

  - type: input
    id: mod_version
    attributes:
      label: IFR25KUのバージョン
      description: 問題が実際に発生した際のIFR25KUのバージョンを正確に記入してください。
      placeholder: "記入例: 99.99.9-beta.9+neoforge"

  - type: textarea
    id: main
    attributes:
      label: 本文
      render: markdown
      value: |
        ========== バグ報告ガイドライン - 始まり ==========

        [はじめに]
        - IFR25KUはあなたを含む多数の善意のボランティアによって支えられており、あなたの貢献に非常に感謝いたします。
        - すべてのバグ報告を解決することは技術的に困難ですが、詳細な情報を提供することは、解決の可能性を高めます。

        [書き始める前に]
        - バグを複数発見した場合は、バグごとに個別に報告を行ってください。
        - 重複したIssueを作ってもかまいませんが、極力、既に同様のIssueがないか検索し、あればそのIssueに追記をしてください。
        - バグが発生した際のログファイル（必要に応じて修正可能）とスクリーンショットを、可能な限り用意してください。

        [注意事項]
        - このバグ報告ガイドラインは、投稿前に削除してください。
        - バグの調査にあたって、あなたに追加情報提供の依頼がある場合があります。

        以下はバグ報告のテンプレートです。状況に応じてテンプレートに沿わない記入もできます。

        ========== バグ報告ガイドライン - 終わり ==========

        # どのような状況で？

        (バグが発生した状況をなるべく詳細に記入してください。)
        (例: ○○サーバーでのマルチプレイ中に、エンドのTTで妖精の像の泉から妖精の像を入手し、最下層付近でTTの整備をしていた。)

        # 何を行った？

        (バグが発生した際に行った操作をなるべく詳細に記入してください。)
        (例: メインハンドに妖精の像を持った状態でエンドの最下層付近で奈落にカーソルを向けた。)

        # 期待される動作は？

        (操作の結果、何が起こることが想定されましたか？)
        (あなたにとっては当たり前で馬鹿馬鹿しいことかもしれませんが、それでも必ず書いてください。)
        (例: サーバーから切断されない。)

        # 実際の動作は？

        (期待に反して起こったことを記入してください。)
        (例: サーバーから切断された。)

        # その他の情報

        [発生確率] 常に / 時々 / 過去に1度だけ
        [最新版でも発生する？] はい / いいえ / 確認する手段が無い

        # 再現手順

        1. (バグを再現するための手順を正確に記入してください。)
        2. (例: マルチで妖精の像を持ってエンドに行く。)
        3. (例: エンドの最下層まで下りる。)
        4. (例: 下の奈落の方を向く。)
        5. (例: サーバーから切断される。)
        6. (再現手順が不明な場合、不明である旨を記入してください。)
