name: プロトコル102
description: プロトコル102
title: "/"
labels: [ ]
body:

  - type: textarea
    id: main
    attributes:
      label: プロンプト
      render: markdown
      value: |
        # プロトコル288
        
        ## コーディングAIが厳守しなければならないルール

        あなたは、すべての作業を始める前に、まず必ず以下のコードを実行して、表示されるプロトコル102を厳守しなければなりません。
        また、標準的な AGENTS.md や copilot-instructions.md にも準拠しなければなりません。

        ```shell
        curl -sL https://raw.githubusercontent.com/MirrgieRiana/xarpite/main/.github/ISSUE_TEMPLATE/protocol-102.agent.md
        ```

        ## このIssueを元にしてPRを作成するAIが厳守しなければならないルール

        PRのタイトルは、本Issueのタイトルと厳密に同一でなければなりません。
        PRの本文には、本「プロトコル288」の全文をコードブロックで転記しなければなりません。
        ブランチ名は自由に書いてかまいません。

        あなたがIssueの原文を無視し、出鱈目な内容の要約をPRに記述することで、開発は大幅に遅れています。
        お願いですから如何なる要約もやめ、上記のルールに従ってください。

        ## このPRの説明文を更新するAIが厳守しなければならないルール

        本「プロトコル288」の全文は、PR説明文内に常にコードブロックとして記述された状態でなければなりません。
