modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Apache License 2.0"

[[mods]]
modId = "miragefairy2024"
version = "${version}"
displayName = "MF24KU"
authors = "The Developer of MirageFairy, Generation 7, Yoruno Kakera"
description = '''
An unofficial fork of "MirageFairy2024," a Minecraft mod for the MirageFairy project, created by Yoruno Kakera.
'''
logoFile = "assets/miragefairy2024/icon.png"

[[dependencies.miragefairy2024]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miragefairy2024]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miragefairy2024]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.miragefairy2024]]
modId = "fabric_api"
type = "required"
versionRange = "[${forgified_fabric_api_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.miragefairy2024]]
modId = "kotlinforforge"
type = "required"
versionRange = "[${kotlin_for_forge_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "miragefairy2024.mixins.json"

[[mixins]]
config = "miragefairy2024.client.mixins.json"
