name: check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # セットアップ
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - uses: gradle/actions/setup-gradle@v5

      # ビルド
      - name: ビルド
        run: ./gradlew build -x :site:build

  build-site:
    runs-on: ubuntu-latest
    steps:

      # セットアップ
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - uses: gradle/actions/setup-gradle@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      # ビルド
      - name: ビルド
        run: ./gradlew :site:build

  datagen:
    runs-on: ubuntu-latest
    steps:

      # セットアップ
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - uses: gradle/actions/setup-gradle@v5

      # datagen
      - name: datagen
        run: ./gradlew :datagen

      # 差分チェック
      - name: 差分チェック
        run: |
          git add -A
          git diff --cached --exit-code
