name: pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      # セットアップ
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - uses: gradle/actions/setup-gradle@v5

      # ビルド
      - name: ビルド
        run: ./gradlew buildPages

      # デプロイ
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/pages
      - name: デプロイ
        id: deployment
        uses: actions/deploy-pages@v4
