name: pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:

      # セットアップ
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
      - uses: gradle/actions/setup-gradle@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      # ビルド
      - name: ビルド
        run: ./gradlew :site:buildSite
        env:
          JEKYLL_ENV: production

      # デプロイ
      - name: デプロイ
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site/build/site --project-name=ifr25ku --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
